#!/usr/bin/env python3
"""
Snapwire CLI — The Agentic Runtime Security Command Center.

Usage:
    python snapwire_cli.py init      Create config.yaml and .env.example
    python snapwire_cli.py check     Run preflight checks (env, DB, LLM)
    python snapwire_cli.py up        Start Flask + Sentinel Proxy
    python snapwire_cli.py aibom     Generate AI Bill of Materials (CycloneDX v1.7)
"""

import os
import sys
import time

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

app = typer.Typer(
    name="snapwire",
    help="Snapwire — Agentic Runtime Security. Intercept, audit, and control AI agent tool calls.",
    no_args_is_help=True,
)

console = Console()

BANNER = r"""
 ⚡ ____                          _
  / ___| _ __   __ _ _ ____      _(_)_ __ ___
  \___ \| '_ \ / _` | '_ \ \ /\ / / | '__/ _ \
   ___) | | | | (_| | |_) \ V  V /| | | |  __/
  |____/|_| |_|\__,_| .__/ \_/\_/ |_|_|  \___|
                     |_|
  Agentic Runtime Security — The 60-Second Governance Layer
  ─────────────────────────────────────────────────────────
"""

DEFAULT_CONFIG = """\
# Snapwire Configuration
# Generated by `snapwire init`
# See https://github.com/getsnapwire for documentation.

admin_email: "{admin_email}"

database:
  url: "{db_url}"

sentinel:
  mode: "audit"          # observe | audit | enforce
  port: 8080
  upstream_url: "https://api.openai.com"

server:
  port: 5000
  workers: 2

governance:
  shadow_mode: false     # true = Observe & Audit (log only, never block)
  hold_window_seconds: 0 # seconds to hold high-risk actions before release
  reasoning_enforcement: true
  strict_reasoning: false

features:
  fuse_breaker: true
  burn_meter: true
  taint_tracking: true
  openclaw: true
  honeypots: true
  snap_tokens: true
"""

DEFAULT_ENV = """\
# ─────────────────────────────────────────────────────────
# Snapwire Environment Variables
# Generated by `snapwire init`
# Copy this to .env and fill in your values.
# ─────────────────────────────────────────────────────────

# ── REQUIRED ──────────────────────────────────────────────

# Admin email(s) — comma-separated for multi-admin
ADMIN_EMAIL=admin@example.com

# Database connection string (PostgreSQL recommended)
DATABASE_URL=postgresql://user:password@host:5432/dbname

# Flask session secret (auto-generated if not set, but sessions won't persist across restarts)
SESSION_SECRET=

# ── LLM PROVIDER (at least one recommended) ──────────────

# Anthropic Claude API key — enables AI-powered rule evaluation, drift detection, tool grading
ANTHROPIC_API_KEY=

# OpenAI GPT API key — alternative LLM provider
OPENAI_API_KEY=

# LLM model override (default: claude-sonnet-4-5 for Anthropic, gpt-4o for OpenAI)
# LLM_MODEL=

# ── NOTIFICATIONS ─────────────────────────────────────────

# Slack webhook URL for alerts, kill-switch notifications, and weekly summaries
SLACK_WEBHOOK_URL=

# SMTP configuration for email notifications
# SMTP_HOST=
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASSWORD=
# SMTP_FROM=noreply@snapwire.ai

# ── SENTINEL PROXY ────────────────────────────────────────

# Sentinel Proxy port (default: 8080)
# SENTINEL_PORT=8080

# Sentinel mode: observe (silent), audit (log+headers), enforce (block bad calls)
# SENTINEL_MODE=audit

# Upstream LLM API URL the proxy forwards to
# UPSTREAM_URL=https://api.openai.com

# Agent ID for the Sentinel Proxy
# SENTINEL_AGENT_ID=sentinel-proxy

# HMAC signing secret for request provenance (optional)
# SNAPWIRE_SIGNING_SECRET=

# ── SECURITY ──────────────────────────────────────────────

# Cloudflare Turnstile (bot protection)
# TURNSTILE_SITE_KEY=
# TURNSTILE_SECRET_KEY=

# ── BYOK (Bring Your Own Key) ────────────────────────────
# Tenants can store encrypted LLM keys in the dashboard.
# The encryption key is derived from SESSION_SECRET.
"""


@app.command()
def init(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing files"),
):
    """Create .snapwire.yaml config and .env.example with all environment variables."""
    console.print(BANNER, style="bold cyan")

    cwd = os.getcwd()
    config_path = os.path.join(cwd, ".snapwire.yaml")
    env_path = os.path.join(cwd, ".env.example")

    if not force:
        existing = []
        if os.path.exists(config_path):
            existing.append(".snapwire.yaml")
        if os.path.exists(env_path):
            existing.append(".env.example")
        if existing:
            console.print(
                f"[yellow]⚠  Already exists:[/yellow] {', '.join(existing)}",
            )
            console.print("   Use [bold]--force[/bold] to overwrite.")
            raise typer.Exit(1)

    admin_email = os.environ.get("ADMIN_EMAIL", "admin@example.com")
    db_url = os.environ.get("DATABASE_URL", "")
    if db_url and "postgresql" in db_url:
        db_display = "(loaded from DATABASE_URL at runtime)"
    elif db_url:
        db_display = "(loaded from DATABASE_URL at runtime)"
    else:
        db_display = "sqlite:///snapwire.db"

    config_content = DEFAULT_CONFIG.format(
        admin_email=admin_email,
        db_url=db_display,
    )

    with open(config_path, "w") as f:
        f.write(config_content)
    console.print(f"[green]✓  Created:[/green] {config_path}")

    with open(env_path, "w") as f:
        f.write(DEFAULT_ENV)
    console.print(f"[green]✓  Created:[/green] {env_path}")

    console.print()
    console.print(Panel(
        "[bold]Next steps:[/bold]\n\n"
        "  1. Copy [cyan].env.example[/cyan] to [cyan].env[/cyan] and fill in your secrets\n"
        "  2. Review [cyan].snapwire.yaml[/cyan] and set your preferences\n"
        "  3. Run [cyan]python snapwire_cli.py check[/cyan] to validate your environment\n"
        "  4. Run [cyan]python snapwire_cli.py up[/cyan] to start Snapwire",
        title="Getting Started",
        border_style="cyan",
    ))


@app.command()
def check():
    """Run preflight checks: environment variables, database, and LLM connectivity."""
    console.print(BANNER, style="bold cyan")
    console.print("[bold]Running Snapwire Preflight Checks...[/bold]\n")

    has_failures = False

    table = Table(
        title="Environment",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    table.add_column("Status", width=8)
    table.add_column("Component", min_width=20)
    table.add_column("Details")

    from check_setup import check_required, check_recommended, check_optional

    for result_set in [check_required(), check_recommended(), check_optional()]:
        for status, name, detail in result_set:
            if status == "PASS":
                icon = "[green]✓ PASS[/green]"
            elif status == "FAIL":
                icon = "[red]✗ FAIL[/red]"
                has_failures = True
            elif status == "WARN":
                icon = "[yellow]⚠ WARN[/yellow]"
            else:
                icon = "[cyan]ℹ INFO[/cyan]"
            table.add_row(icon, name, detail)

    console.print(table)
    console.print()

    db_table = Table(
        title="Database",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    db_table.add_column("Status", width=8)
    db_table.add_column("Component", min_width=20)
    db_table.add_column("Details")

    from check_setup import check_database
    db_status, db_name, db_detail = check_database()
    if db_status == "PASS":
        db_icon = "[green]✓ PASS[/green]"
    elif db_status == "FAIL":
        db_icon = "[red]✗ FAIL[/red]"
        has_failures = True
    else:
        db_icon = "[yellow]⚠ WARN[/yellow]"

    db_table.add_row(db_icon, db_name, db_detail)
    console.print(db_table)
    console.print()

    llm_table = Table(
        title="LLM Connectivity",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    llm_table.add_column("Status", width=8)
    llm_table.add_column("Component", min_width=20)
    llm_table.add_column("Details")

    llm_status = _check_llm()
    llm_table.add_row(llm_status[0], llm_status[1], llm_status[2])
    console.print(llm_table)
    console.print()

    if has_failures:
        console.print(
            Panel(
                "[red bold]✗ Preflight failed.[/red bold]\n\n"
                "Fix the FAIL items above before running [cyan]snapwire up[/cyan].\n"
                "Required environment variables can be set in your .env or Replit Secrets.",
                title="Result",
                border_style="red",
            )
        )
        sys.exit(1)
    else:
        console.print(
            Panel(
                "[green bold]✓ All checks passed. Snapwire is ready.[/green bold]\n\n"
                "Run [cyan]python snapwire_cli.py up[/cyan] to start.",
                title="Result",
                border_style="green",
            )
        )


def _check_llm():
    has_anthropic = bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())
    has_openai = bool(os.environ.get("OPENAI_API_KEY", "").strip())

    if not has_anthropic and not has_openai:
        return (
            "[yellow]⚠ WARN[/yellow]",
            "LLM 1-Token Test",
            "No API key set (ANTHROPIC_API_KEY or OPENAI_API_KEY). AI features disabled. Deterministic rules still work.",
        )

    provider = "anthropic" if has_anthropic else "openai"

    try:
        if provider == "anthropic":
            import anthropic
            client = anthropic.Anthropic()
            msg = client.messages.create(
                model=os.environ.get("LLM_MODEL", "claude-sonnet-4-5"),
                max_tokens=1,
                messages=[{"role": "user", "content": "ping"}],
            )
            return (
                "[green]✓ PASS[/green]",
                "LLM 1-Token Test",
                f"Anthropic Claude reachable (model: {msg.model})",
            )
        else:
            from openai import OpenAI
            client = OpenAI()
            resp = client.chat.completions.create(
                model=os.environ.get("LLM_MODEL", "gpt-4o"),
                max_tokens=1,
                messages=[{"role": "user", "content": "ping"}],
            )
            return (
                "[green]✓ PASS[/green]",
                "LLM 1-Token Test",
                f"OpenAI reachable (model: {resp.model})",
            )
    except Exception as e:
        err = str(e)[:120]
        return (
            "[yellow]⚠ WARN[/yellow]",
            "LLM 1-Token Test",
            f"{provider} key set but call failed: {err}. AI features may be unavailable.",
        )


@app.command()
def up(
    port: int = typer.Option(5000, "--port", "-p", help="Flask server port"),
    proxy: bool = typer.Option(True, "--proxy/--no-proxy", help="Start Sentinel Proxy sidecar (default: enabled)"),
    sentinel_port: int = typer.Option(8080, "--sentinel-port", help="Sentinel Proxy port"),
    mode: str = typer.Option("audit", "--mode", "-m", help="Sentinel mode: observe, audit, enforce"),
    workers: int = typer.Option(2, "--workers", "-w", help="Gunicorn worker count"),
):
    """Start Snapwire server and Sentinel Proxy."""
    console.print(BANNER, style="bold cyan")

    import subprocess
    import signal as sig

    info_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    info_table.add_column("Key", style="bold")
    info_table.add_column("Value", style="cyan")
    info_table.add_row("Flask", f"http://0.0.0.0:{port}")
    if proxy:
        info_table.add_row("Sentinel Proxy", f"http://0.0.0.0:{sentinel_port}")
        info_table.add_row("Proxy Mode", mode.upper())
        upstream = os.environ.get("UPSTREAM_URL", "https://api.openai.com")
        info_table.add_row("Upstream", upstream)
    info_table.add_row("Workers", str(workers))
    admin = os.environ.get("ADMIN_EMAIL", "not set")
    info_table.add_row("Admin", admin)

    console.print(Panel(info_table, title="[bold]Snapwire Starting[/bold]", border_style="cyan"))
    console.print()

    processes = []

    flask_env = os.environ.copy()
    flask_env["PORT"] = str(port)

    is_dev = os.environ.get("REPL_SLUG") or os.environ.get("REPLIT_DEV_DOMAIN")

    if is_dev:
        flask_cmd = [sys.executable, "main.py"]
    else:
        flask_cmd = [
            sys.executable, "-m", "gunicorn",
            "--bind", f"0.0.0.0:{port}",
            "--workers", str(workers),
            "--timeout", "120",
            "main:app",
        ]

    console.print(f"[green]▶[/green]  Starting Flask server on port {port}...")
    flask_proc = subprocess.Popen(flask_cmd, env=flask_env)
    processes.append(("Flask", flask_proc))

    if proxy:
        try:
            import importlib
            importlib.import_module("sentinel")
        except ImportError:
            console.print("[yellow]⚠  Sentinel module not found. Starting without proxy.[/yellow]")
            console.print("   Use [cyan]--no-proxy[/cyan] to suppress this warning.\n")
            proxy = False

    if proxy:
        console.print(f"[green]▶[/green]  Starting Sentinel Proxy on port {sentinel_port} ({mode} mode)...")
        sentinel_env = os.environ.copy()
        sentinel_env["SENTINEL_PORT"] = str(sentinel_port)
        sentinel_env["SENTINEL_MODE"] = mode
        sentinel_env["SNAPWIRE_URL"] = f"http://localhost:{port}"
        sentinel_cmd = [sys.executable, "-m", "sentinel"]
        sentinel_proc = subprocess.Popen(sentinel_cmd, env=sentinel_env)
        processes.append(("Sentinel", sentinel_proc))

    console.print()
    console.print("[bold green]✓  Snapwire is running.[/bold green]  Press Ctrl+C to stop.\n")

    def shutdown(signum, frame):
        console.print("\n[yellow]Shutting down...[/yellow]")
        for name, proc in processes:
            if proc.poll() is None:
                console.print(f"  Stopping {name}...")
                proc.terminate()
        for name, proc in processes:
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        console.print("[green]✓  Snapwire stopped.[/green]")
        sys.exit(0)

    sig.signal(sig.SIGINT, shutdown)
    sig.signal(sig.SIGTERM, shutdown)

    try:
        while True:
            for name, proc in processes:
                ret = proc.poll()
                if ret is not None:
                    if name == "Sentinel":
                        console.print(f"[yellow]⚠  Sentinel Proxy exited (code {ret}). Flask continues running.[/yellow]")
                        console.print("   Restart with [cyan]--no-proxy[/cyan] to skip proxy, or check sentinel config.\n")
                        processes = [(n, p) for n, p in processes if n != "Sentinel"]
                        break
                    else:
                        console.print(f"[red]✗  {name} exited with code {ret}[/red]")
                        shutdown(None, None)
            time.sleep(1)
    except KeyboardInterrupt:
        shutdown(None, None)


@app.command()
def aibom(
    tenant: str = typer.Option("", "--tenant", "-t", help="Tenant ID (default: global)"),
    days: int = typer.Option(30, "--days", "-d", help="Audit log lookback window in days"),
    output: str = typer.Option("", "--output", "-o", help="Output file path (default: auto-generated)"),
):
    """Generate an AI Bill of Materials (CycloneDX v1.7 JSON)."""
    console.print(BANNER, style="bold cyan")

    if days < 1:
        console.print(Panel(
            "[red bold]✗ Invalid --days value.[/red bold]\n\n"
            "Days must be at least 1. Example: [cyan]snapwire aibom --days 30[/cyan]",
            title="Error",
            border_style="red",
        ))
        raise typer.Exit(1)

    if not os.environ.get("DATABASE_URL", "").strip():
        console.print(Panel(
            "[red bold]✗ DATABASE_URL not set.[/red bold]\n\n"
            "The AIBOM generator requires database access.\n"
            "Set DATABASE_URL in your environment or .env file, then retry.\n"
            "Run [cyan]snapwire check[/cyan] to validate your setup.",
            title="Error",
            border_style="red",
        ))
        raise typer.Exit(1)

    from rich.progress import Progress, SpinnerColumn, TextColumn

    try:
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            progress.add_task(description="Generating AIBOM...", total=None)

            from app import app as flask_app, db
            with flask_app.app_context():
                from src.aibom_generator import generate_aibom

                tenant_id = tenant if tenant else None
                bom = generate_aibom(tenant_id=tenant_id, days=days)
    except Exception as e:
        err = str(e)[:200]
        console.print(Panel(
            f"[red bold]✗ AIBOM generation failed.[/red bold]\n\n"
            f"Error: {err}\n\n"
            "Possible causes:\n"
            "  - Database not reachable or migrations not applied\n"
            "  - Missing required tables (run the app once to auto-migrate)\n\n"
            "Run [cyan]snapwire check[/cyan] to diagnose.",
            title="Error",
            border_style="red",
        ))
        raise typer.Exit(1)

    if not output:
        ts = time.strftime("%Y%m%d_%H%M%S")
        label = tenant if tenant else "global"
        output = os.path.join(os.getcwd(), f"snapwire_aibom_{label}_{ts}.json")

    import json
    with open(output, "w") as f:
        json.dump(bom, f, indent=2, default=str)

    component_count = len(bom.get("components", []))
    service_count = len(bom.get("services", []))
    serial = bom.get("serialNumber", "—")
    spec_version = bom.get("specVersion", "—")
    timestamp = bom.get("metadata", {}).get("timestamp", "—")

    summary_table = Table(box=box.ROUNDED, show_header=False, padding=(0, 2))
    summary_table.add_column("Key", style="bold")
    summary_table.add_column("Value", style="cyan")
    summary_table.add_row("Specification", f"CycloneDX v{spec_version}")
    summary_table.add_row("Serial Number", serial)
    summary_table.add_row("Generated", timestamp)
    summary_table.add_row("Components", str(component_count))
    summary_table.add_row("Services", str(service_count))
    summary_table.add_row("Lookback", f"{days} days")
    summary_table.add_row("Tenant", tenant if tenant else "global")
    summary_table.add_row("Output", output)

    file_size = os.path.getsize(output)
    size_str = f"{file_size:,} bytes" if file_size < 1024 else f"{file_size / 1024:.1f} KB"
    summary_table.add_row("File Size", size_str)

    console.print(Panel(
        summary_table,
        title="[bold green]✓ AIBOM Generated[/bold green]",
        border_style="green",
    ))

    console.print(f"\n[dim]Verify integrity:[/dim] python -c \"from src.aibom_generator import verify_aibom_hmac; print(verify_aibom_hmac('{output}'))\"")


if __name__ == "__main__":
    app()
