#!/usr/bin/env python3
"""
Snapwire CLI — The Agentic Runtime Security Command Center.

Usage:
    python snapwire_cli.py init     Create a .snapwire.yaml config file
    python snapwire_cli.py check    Run preflight checks (env, DB, LLM)
    python snapwire_cli.py up       Start Snapwire (Flask + optional Sentinel Proxy)
"""

import os
import sys
import time

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

app = typer.Typer(
    name="snapwire",
    help="Snapwire — Agentic Runtime Security. Intercept, audit, and control AI agent tool calls.",
    no_args_is_help=True,
)

console = Console()

BANNER = r"""
 ⚡ ____                          _
  / ___| _ __   __ _ _ ____      _(_)_ __ ___
  \___ \| '_ \ / _` | '_ \ \ /\ / / | '__/ _ \
   ___) | | | | (_| | |_) \ V  V /| | | |  __/
  |____/|_| |_|\__,_| .__/ \_/\_/ |_|_|  \___|
                     |_|
  Agentic Runtime Security — The 60-Second Governance Layer
  ─────────────────────────────────────────────────────────
"""

DEFAULT_CONFIG = """\
# Snapwire Configuration
# Generated by `snapwire init`
# See https://github.com/getsnapwire for documentation.

admin_email: "{admin_email}"

database:
  url: "{db_url}"

sentinel:
  mode: "audit"          # observe | audit | enforce
  port: 8080
  upstream_url: "https://api.openai.com"

server:
  port: 5000
  workers: 2

governance:
  shadow_mode: false     # true = Observe & Audit (log only, never block)
  hold_window_seconds: 0 # seconds to hold high-risk actions before release
  reasoning_enforcement: true
  strict_reasoning: false

features:
  fuse_breaker: true
  burn_meter: true
  taint_tracking: true
  openclaw: true
  honeypots: true
  snap_tokens: true
"""


@app.command()
def init(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing config file"),
):
    """Create a .snapwire.yaml configuration file with sensible defaults."""
    console.print(BANNER, style="bold cyan")
    config_path = os.path.join(os.getcwd(), ".snapwire.yaml")

    if os.path.exists(config_path) and not force:
        console.print(
            f"[yellow]⚠  Config file already exists:[/yellow] {config_path}",
        )
        console.print("   Use [bold]--force[/bold] to overwrite.")
        raise typer.Exit(1)

    admin_email = os.environ.get("ADMIN_EMAIL", "admin@example.com")
    db_url = os.environ.get("DATABASE_URL", "")
    if db_url and "postgresql" in db_url:
        db_display = "postgresql://***@" + db_url.split("@")[-1] if "@" in db_url else "(set via DATABASE_URL env var)"
    elif db_url:
        db_display = db_url
    else:
        db_display = "sqlite:///snapwire.db"

    config_content = DEFAULT_CONFIG.format(
        admin_email=admin_email,
        db_url=db_display,
    )

    with open(config_path, "w") as f:
        f.write(config_content)

    console.print(f"[green]✓  Config created:[/green] {config_path}\n")

    console.print(Panel(
        "[bold]Next steps:[/bold]\n\n"
        "  1. Review .snapwire.yaml and set your preferences\n"
        "  2. Run [cyan]python snapwire_cli.py check[/cyan] to validate your environment\n"
        "  3. Run [cyan]python snapwire_cli.py up[/cyan] to start Snapwire",
        title="Getting Started",
        border_style="cyan",
    ))


@app.command()
def check():
    """Run preflight checks: environment variables, database, and LLM connectivity."""
    console.print(BANNER, style="bold cyan")
    console.print("[bold]Running Snapwire Preflight Checks...[/bold]\n")

    has_failures = False

    table = Table(
        title="Environment",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    table.add_column("Status", width=8)
    table.add_column("Component", min_width=20)
    table.add_column("Details")

    from check_setup import check_required, check_recommended, check_optional

    for result_set in [check_required(), check_recommended(), check_optional()]:
        for status, name, detail in result_set:
            if status == "PASS":
                icon = "[green]✓ PASS[/green]"
            elif status == "FAIL":
                icon = "[red]✗ FAIL[/red]"
                has_failures = True
            elif status == "WARN":
                icon = "[yellow]⚠ WARN[/yellow]"
            else:
                icon = "[cyan]ℹ INFO[/cyan]"
            table.add_row(icon, name, detail)

    console.print(table)
    console.print()

    db_table = Table(
        title="Database",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    db_table.add_column("Status", width=8)
    db_table.add_column("Component", min_width=20)
    db_table.add_column("Details")

    from check_setup import check_database
    db_status, db_name, db_detail = check_database()
    if db_status == "PASS":
        db_icon = "[green]✓ PASS[/green]"
    elif db_status == "FAIL":
        db_icon = "[red]✗ FAIL[/red]"
        has_failures = True
    else:
        db_icon = "[yellow]⚠ WARN[/yellow]"

    db_table.add_row(db_icon, db_name, db_detail)
    console.print(db_table)
    console.print()

    llm_table = Table(
        title="LLM Connectivity",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    llm_table.add_column("Status", width=8)
    llm_table.add_column("Component", min_width=20)
    llm_table.add_column("Details")

    llm_status = _check_llm()
    llm_table.add_row(llm_status[0], llm_status[1], llm_status[2])
    console.print(llm_table)
    console.print()

    if has_failures:
        console.print(
            Panel(
                "[red bold]✗ Preflight failed.[/red bold]\n\n"
                "Fix the FAIL items above before running [cyan]snapwire up[/cyan].\n"
                "Required environment variables can be set in your .env or Replit Secrets.",
                title="Result",
                border_style="red",
            )
        )
        sys.exit(1)
    else:
        console.print(
            Panel(
                "[green bold]✓ All checks passed. Snapwire is ready.[/green bold]\n\n"
                "Run [cyan]python snapwire_cli.py up[/cyan] to start.",
                title="Result",
                border_style="green",
            )
        )


def _check_llm():
    has_anthropic = bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())
    has_openai = bool(os.environ.get("OPENAI_API_KEY", "").strip())

    if not has_anthropic and not has_openai:
        return (
            "[yellow]⚠ WARN[/yellow]",
            "LLM 1-Token Test",
            "No API key set (ANTHROPIC_API_KEY or OPENAI_API_KEY). AI features disabled. Deterministic rules still work.",
        )

    provider = "anthropic" if has_anthropic else "openai"

    try:
        if provider == "anthropic":
            import anthropic
            client = anthropic.Anthropic()
            msg = client.messages.create(
                model=os.environ.get("LLM_MODEL", "claude-sonnet-4-5"),
                max_tokens=1,
                messages=[{"role": "user", "content": "ping"}],
            )
            return (
                "[green]✓ PASS[/green]",
                "LLM 1-Token Test",
                f"Anthropic Claude reachable (model: {msg.model})",
            )
        else:
            from openai import OpenAI
            client = OpenAI()
            resp = client.chat.completions.create(
                model=os.environ.get("LLM_MODEL", "gpt-4o"),
                max_tokens=1,
                messages=[{"role": "user", "content": "ping"}],
            )
            return (
                "[green]✓ PASS[/green]",
                "LLM 1-Token Test",
                f"OpenAI reachable (model: {resp.model})",
            )
    except Exception as e:
        err = str(e)[:120]
        return (
            "[yellow]⚠ WARN[/yellow]",
            "LLM 1-Token Test",
            f"{provider} key set but call failed: {err}. AI features may be unavailable.",
        )


@app.command()
def up(
    port: int = typer.Option(5000, "--port", "-p", help="Flask server port"),
    proxy: bool = typer.Option(False, "--proxy", help="Also start the Sentinel Proxy sidecar"),
    sentinel_port: int = typer.Option(8080, "--sentinel-port", help="Sentinel Proxy port"),
    mode: str = typer.Option("audit", "--mode", "-m", help="Sentinel mode: observe, audit, enforce"),
    workers: int = typer.Option(2, "--workers", "-w", help="Gunicorn worker count"),
):
    """Start Snapwire server (and optionally the Sentinel Proxy)."""
    console.print(BANNER, style="bold cyan")

    import subprocess
    import signal as sig

    info_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    info_table.add_column("Key", style="bold")
    info_table.add_column("Value", style="cyan")
    info_table.add_row("Flask", f"http://0.0.0.0:{port}")
    if proxy:
        info_table.add_row("Sentinel Proxy", f"http://0.0.0.0:{sentinel_port}")
        info_table.add_row("Proxy Mode", mode.upper())
        upstream = os.environ.get("UPSTREAM_URL", "https://api.openai.com")
        info_table.add_row("Upstream", upstream)
    info_table.add_row("Workers", str(workers))
    admin = os.environ.get("ADMIN_EMAIL", "not set")
    info_table.add_row("Admin", admin)

    console.print(Panel(info_table, title="[bold]Snapwire Starting[/bold]", border_style="cyan"))
    console.print()

    processes = []

    flask_env = os.environ.copy()
    flask_env["PORT"] = str(port)

    is_dev = os.environ.get("REPL_SLUG") or os.environ.get("REPLIT_DEV_DOMAIN")

    if is_dev:
        flask_cmd = [sys.executable, "main.py"]
    else:
        flask_cmd = [
            sys.executable, "-m", "gunicorn",
            "--bind", f"0.0.0.0:{port}",
            "--workers", str(workers),
            "--timeout", "120",
            "main:app",
        ]

    console.print(f"[green]▶[/green]  Starting Flask server on port {port}...")
    flask_proc = subprocess.Popen(flask_cmd, env=flask_env)
    processes.append(("Flask", flask_proc))

    sentinel_proc = None
    if proxy:
        console.print(f"[green]▶[/green]  Starting Sentinel Proxy on port {sentinel_port} ({mode} mode)...")
        sentinel_env = os.environ.copy()
        sentinel_env["SENTINEL_PORT"] = str(sentinel_port)
        sentinel_env["SENTINEL_MODE"] = mode
        sentinel_env["SNAPWIRE_URL"] = f"http://localhost:{port}"
        sentinel_cmd = [sys.executable, "-m", "sentinel"]
        sentinel_proc = subprocess.Popen(sentinel_cmd, env=sentinel_env)
        processes.append(("Sentinel", sentinel_proc))

    console.print()
    console.print("[bold green]✓  Snapwire is running.[/bold green]  Press Ctrl+C to stop.\n")

    def shutdown(signum, frame):
        console.print("\n[yellow]Shutting down...[/yellow]")
        for name, proc in processes:
            if proc.poll() is None:
                console.print(f"  Stopping {name}...")
                proc.terminate()
        for name, proc in processes:
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        console.print("[green]✓  Snapwire stopped.[/green]")
        sys.exit(0)

    sig.signal(sig.SIGINT, shutdown)
    sig.signal(sig.SIGTERM, shutdown)

    try:
        while True:
            for name, proc in processes:
                ret = proc.poll()
                if ret is not None:
                    console.print(f"[red]✗  {name} exited with code {ret}[/red]")
                    shutdown(None, None)
            time.sleep(1)
    except KeyboardInterrupt:
        shutdown(None, None)


if __name__ == "__main__":
    app()
